---
# tasks file for rhel_patching

# 01: common RHEL patching tasks in an Ansible tasks file

- name: Get uptime
  ansible.builtin.command: /usr/bin/uptime
  register: register_uptime
  tags: register_uptime
      
- name: Print print
  ansible.builtin.debug:
    var: register_uptime.stdout_lines
  tags: register_uptime

- name: Update package cache
  ansible.builtin.yum:
    name: "*"
    state: latest
    update_cache: "{{ update_cache }}"
  tags: update_cache

- name: Install required packages
  ansible.builtin.yum:
    name: "{{ install_packages }}"
    state: present
  tags: install_packages

- name: Remove unnecessary packages
  ansible.builtin.yum:
    name: "{{ remove_packages }}"
    state: absent
  tags: remove_packages

- name: Install security updates
  ansible.builtin.yum:
    name: "*"
    state: latest
    security: "{{ install_security_updates }}"
  tags: install_security_updates

- name: Ensure SELinux is enforcing
  ansible.builtin.selinux:
    policy: targeted
    state: "{{ selinux_state }}"
  tags: selinux_state

- name: Configure firewalld
  ansible.builtin.firewalld:
    zone: "{{ firewalld_zone }}"
    service: "{{ firewalld_service }}"
    state: enabled
  tags: firewalld

- name: Enable and start required services
  ansible.builtin.systemd:
    name: "{{ enable_services }}"
    state: started
    enabled: yes
  tags: enable_services

- name: Disable and stop unnecessary services
  ansible.builtin.systemd:
    name: "{{ disable_services }}"
    state: stopped
    enabled: no
  tags: disable_services

- name: Set kernel parameters
  ansible.builtin.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: yes
  loop: "{{ kernel_parameters|dict2items }}"
  tags: kernel_parameters

# cat: /etc/dnf/automatic.conf: No such file or directory
- name: Configure automatic updates
  ansible.builtin.template:
    src: dnf-automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: 0644
  tags: configure_automatic_updates

# 02: tasks covering tasks covering common yum operations, 
# such as managing repos, listing available patches

- name: Add a new repository
  ansible.builtin.yum_repository:
    name: "{{ repo_name }}"
    description: "{{ repo_description }}"
    baseurl: "{{ repo_baseurl }}"
    gpgcheck: "{{ repo_gpgcheck }}"
    enabled: "{{ repo_enabled }}"
  tags: add_repository

- name: Remove a repository
  ansible.builtin.yum_repository:
    name: "{{ repo_name }}"
    state: absent
  tags: remove_repository

- name: Enable a repository
  ansible.builtin.yum_repository:
    name: "{{ repo_name }}"
    enabled: yes
  tags: enable_repository

- name: Disable a repository
  ansible.builtin.yum_repository:
    name: "{{ repo_name }}"
    enabled: no
  tags: disable_repository

- name: List available updates
  ansible.builtin.command:
    cmd: yum check-update
  register: available_updates
  changed_when: False
  tags: list_updates

- name: Display available updates
  ansible.builtin.debug:
    var: available_updates.stdout_lines
  tags: list_updates

- name: List installed packages
  ansible.builtin.package_facts:
    manager: auto
  tags: list_installed_packages

- name: Display installed packages
  ansible.builtin.debug:
    var: ansible_facts.packages
  tags: list_installed_packages

- name: Install a specific package version
  ansible.builtin.yum:
    name: "{{ package_name }}-{{ package_version }}"
    state: present
  tags: install_specific_version

- name: Downgrade a package
  ansible.builtin.yum:
    name: "{{ package_name }}"
    state: present
    allow_downgrade: yes
  tags: downgrade_package

# 03: common tasks for Red Hat Satellite clients 
# and Red Hat Insights clients

- name: Install Satellite client packages
  ansible.builtin.yum:
    name:
      - katello-agent
      - katello-host-tools
      - katello-host-tools-tracer
    state: present
  tags: install_satellite_client

# The error appears to be in '/runner/project/roles/poc_packages/rhel_patching/tasks/main.yml': line 155, column 3, but may
# be elsewhere in the file depending on the exact syntax problem.

# - name: Register Satellite client
#   ansible.builtin.redhat_subscription:
#     state: present
#     username: "{{ satellite_username }}"
#     password: "{{ satellite_password }}"
#     org_id: "{{ satellite_org_id }}"
#     activationkey: "{{ satellite_activation_key }}"
#   tags: register_satellite_client

- name: Enable Red Hat Insights
  ansible.builtin.package:
    name: insights-client
    state: present
  tags: install_insights_client

- name: Register Red Hat Insights client
  ansible.builtin.command:
    cmd: insights-client --register
  tags: register_insights_client

- name: Check status of Red Hat Insights client
  ansible.builtin.command:
    cmd: insights-client --status
  changed_when: false
  register: register_insights_client_status
  tags: insights_client_status

- name: Print status of Red Hat Insights client
  ansible.builtin.debug:
    msg: "{{ register_insights_client_status.stdout_lines }}"
  tags: insights_client_status

- name: Configure Red Hat Insights client
  ansible.builtin.template:
    src: insights-client.conf.j2
    dest: /etc/insights-client/insights-client.conf
    owner: root
    group: root
    mode: 0644
  tags: configure_insights_client

# insights-client: error: unrecognized arguments: --autoconfig
# - name: Enable Red Hat Insights auto-config
#   ansible.builtin.command:
#     cmd: insights-client --autoconfig
#   tags: insights_auto_config

- name: Run Red Hat Insights client
  ansible.builtin.command:
    cmd: insights-client --check-result
  tags: run_insights_client

# - name: Unregister Red Hat Satellite client
#   ansible.builtin.redhat_subscription:
#     state: absent
#     username: "{{ satellite_username }}"
#     password: "{{ satellite_password }}"
#   tags: unregister_satellite_client

- name: Unregister Red Hat Insights client
  ansible.builtin.command:
    cmd: insights-client --unregister
  tags: unregister_insights_client

- name: Remove Red Hat Insights client
  ansible.builtin.package:
    name: insights-client
    state: absent
  tags: remove_insights_client
